# Generated by Django 5.0.6 on 2026-07-02 17:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sync_version', models.IntegerField(default=0)),
                ('operation_type', models.CharField(choices=[('sale', 'Sale'), ('payment', 'Payment'), ('expense', 'Expense'), ('customer', 'Customer'), ('supplier', 'Supplier'), ('product', 'Product'), ('stock_adjustment', 'Stock Adjustment'), ('transfer', 'Transfer'), ('purchase', 'Purchase')], max_length=20)),
                ('operation_id', models.UUIDField(help_text='Client-generated UUID for idempotency')),
                ('client_mutation_id', models.CharField(help_text='Unique ID to prevent duplicates', max_length=100, unique=True)),
                ('data', models.JSONField(help_text='The operation data to be processed')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at_local', models.DateTimeField(help_text='Timestamp when created offline')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('attempt_count', models.IntegerField(default=0)),
                ('server_response', models.JSONField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_operations', to='branches.branch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_operations', to='tenants.tenant')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pending_operations',
                'ordering': ['created_at_local'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sync_version', models.IntegerField(default=0)),
                ('sync_type', models.CharField(choices=[('pull', 'Pull'), ('push', 'Push'), ('full', 'Full Sync')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('client_version', models.CharField(blank=True, help_text='Client app version', max_length=100)),
                ('device_id', models.CharField(blank=True, max_length=255)),
                ('device_name', models.CharField(blank=True, max_length=255)),
                ('records_pulled', models.IntegerField(default=0)),
                ('records_pushed', models.IntegerField(default=0)),
                ('records_failed', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('error_traceback', models.TextField(blank=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='branches.branch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='tenants.tenant')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sync_logs',
                'ordering': ['-started_at'],
            },
        ),
    ]
